### ISSUE TITLE
Self signed certificate

### ISSUE THREAD

**Issue by christianjames** [iagolaguna/vscodefy#1]
After installing the extension, nothing happens when clicking the buttons, as the image below:

![image](https://user-images.githubusercontent.com/5203020/44356826-d7545000-a486-11e8-8848-9b2747f0cf09.png)

I tried using the `Spotify: Pick a device` command, but it gave the error as pictured below:

![image](https://user-images.githubusercontent.com/5203020/44356811-d0c5d880-a486-11e8-8be6-062bd6ce1414.png)

I'm using:
Windows 10

![image](https://user-images.githubusercontent.com/5203020/44357407-58f8ad80-a488-11e8-97fe-1b30140b40d6.png)

BTW, Can be my network with firewall, I'll check.

**Comment by iagolaguna** [comment]
has an issue about proxy open on vscode repository https://github.com/Microsoft/vscode/issues/12588
see that, i think the referenced merge isn't enough to fix this bug , but i will put this in production, please @christianjames let me know if this error persist.
