### ISSUE TITLE
Does not connect

### ISSUE THREAD

**Issue by Censoretti** [iagolaguna/vscodefy#17]
When i try to login with my spotify account, it shows me this message: 
INVALID_CLIENT: Invalid redirect URI

and i cannot login with my spotify account

**Comment by iagolaguna** [comment]
Hello, @dagashy thank you for your feedback, I will see what's is happening with the extension ASAP.

**Comment by iagolaguna** [comment]
@dagashy  was a problem with netlify they changed the suffix .com to .app and this broke the OAuth from Spotify, but now it's fixed
