### ISSUE TITLE
Request failed with status code 500

### ISSUE THREAD

**Issue by Censoretti** [iagolaguna/vscodefy#18]
after i got the OAUTH code, i try to configure i recieve this error:

Request failed with status code 500

yesterday I thought that was my own internet, or something with the server, but i try too many times today, and nothing

sorry if i bother you guys with silly things :x
~but thanks for the help from yesterday problem, and for this too~

**Comment by iagolaguna** [comment]
@dagashy the server is having some trouble to process all requests, I will take a look at it, if you get other errors, please submit to us be able to improve the extension.

**Comment by iagolaguna** [comment]
@dagashy, I'm happy to say that the bug was fixed, now you can use the extension :), let me know if you have any other problems.

If anyone has the same problem or is already logged, please logout from extension and log in again, you can search for the command `Spotify: Logout`
