### ISSUE TITLE
Command 'Spotify: Pick a device' resulted in an error (Request failed with status code 403)

### ISSUE THREAD

**Issue by DroidZed** [iagolaguna/vscodefy#21]
When picking a device, the error, player buttons and song name show up but the buttons are not clickable...
Is it because I'm using a cracked Spotify client with my free account ? This also happens for the Web-Player too ...

**Comment by iagolaguna** [comment]
Probably since this extension only works for premium accounts because only premium accounts have access to the Control's API

**Comment by DroidZed** [comment]
What a bummer....
