### ISSUE TITLE
Login button didn't work

### ISSUE THREAD

**Issue by elizeugba** [iagolaguna/vscodefy#6]
I tried to sign in through the login button, as showed in the gif, but, for some unkown reason, it didn't open the login page on my browser.  I tried to do execute vscode as admin, and redo the process, but it didn't work.

For what I could see, seems that it did actualy executed the function that opens the browser, but it wasn't able to open a new tab.

Browser: Google chrome 70.0.3538.110
Vscode: 1.29.1

For anyone having the same issue, just access the url directly: https://vscodefy.netlify.com/.

**Comment by elizeugba** [comment]
This error only occurred on my PC, I tested on my laptop and my job's computer and it worked fine. So, you can mark this as closed.

**Comment by iagolaguna** [comment]
@elizeugba, maybe you can provide more information, inside of vscode, Help -> Toggle Developer Tools,
this will open a Developer Tool like Chrome, can you test again and see if appear some error in console ?
